SneakerStore/SneakerStore/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('store.urls'))
]

SneakerStore/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "store"

urlpatterns = [
                  path('', views.index, name='index'),
                  path('registar', views.registar, name='registar'),
                  path('login', views.login_view, name='login_view'),
                  path('perfil', views.perfil, name='perfil'),
                  path('logout', views.logout_view, name='logout'),
                  path('editar_perfil/', views.editar_perfil, name='editar_perfil'),
                  path('login', auth_views.LoginView.as_view(), name='login'),
                  path('logout', auth_views.LogoutView.as_view(), name='logout'),
                  path('remover_carrinho/<int:sneaker_id>/', views.remover_carrinho, name='remover_carrinho'),
                  path('adicionar_carrinho/<int:sneaker_id>/', views.adicionar_carrinho, name='adicionar_carrinho'),
                  path('carrinho', views.carrinho, name='carrinho'),
                  path('favoritos', views.favoritos, name='favoritos'),
                  path('adicionar_favoritos/<int:sneaker_id>/', views.adicionar_favoritos, name='adicionar_favoritos'),
                  path('remover_favoritos/<int:sneaker_id>/', views.remover_favoritos, name='remover_favoritos'),
                  path('catalogo/', views.catalogo, name='catalogo'),
                  path('sobre_nos', views.sobre_nos, name='sobre_nos'),
                  path('detalhes/<int:sneaker_id>/', views.detalhes, name='detalhes'),
                  path('encomendas/', views.encomendas, name='encomendas'),
                  path('finalizar_compra/', views.finalizar_compra, name='finalizar_compra'),
                  path('editar_sneaker/<int:sneaker_id>/', views.editar_sneaker, name='editar_sneaker'),
                  path('remover_sneaker/<int:sneaker_id>/', views.remover_sneaker, name='remover_sneaker'),
                  path('adicionar/', views.adicionar_sneaker, name='adicionar_sneaker'),
                  path('encomendas/<int:encomenda_id>/status/', views.update_encomenda_status,
                       name='update_encomenda_status'),
                  path('recomendados/', views.recomendados, name='recomendados'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SneakerStore/store/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime, timedelta


class Cliente(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    morada = models.CharField(max_length=255)
    telemovel = models.IntegerField()
    nif = models.IntegerField()
    imagem = models.ImageField(default='store/images/default_profile_pic.png')
    categoria_preferida = models.ForeignKey('Categoria', on_delete=models.SET_NULL, null=True)
    tamanho_preferido = models.ForeignKey('Tamanho', on_delete=models.SET_NULL, null=True)
    marca_preferida = models.ForeignKey('Marca', on_delete=models.SET_NULL, null=True)


class EmpregadoLoja(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    morada = models.CharField(max_length=255)
    nif = models.IntegerField()
    telemovel = models.IntegerField()
    imagem = models.ImageField(default='store/images/default_profile_pic.png')


class Marca(models.Model):
    nome = models.CharField(max_length=255)
    pais = models.CharField(max_length=255)


class Tamanho(models.Model):
    tamanho = models.CharField(max_length=50)


class Categoria(models.Model):
    nome = models.CharField(max_length=255)


class Sneaker(models.Model):
    nome = models.CharField(max_length=255)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    categoria = models.ForeignKey('Categoria', on_delete=models.SET_NULL, null=True)
    tamanho = models.ForeignKey(Tamanho, on_delete=models.CASCADE)
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    imagem = models.ImageField()
    quantidade_stock = models.IntegerField()


class Carrinho(models.Model):
    cliente = models.OneToOneField(Cliente, on_delete=models.CASCADE)
    ativo = models.BooleanField()
    data_inatividade = models.DateField(default=datetime.now() + timedelta(days=7))


class ItemCarrinho(models.Model):
    sneaker = models.ForeignKey(Sneaker, on_delete=models.CASCADE)
    carrinho = models.ForeignKey(Carrinho, on_delete=models.CASCADE)
    quantidade = models.IntegerField()


class Encomenda(models.Model):
    STATUS_CHOICES = [
        ('processamento', 'Em Processamento'),
        ('cancelada', 'Cancelada'),
        ('entregue', 'Entregue'),
    ]
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    data = models.DateTimeField()
    status = models.CharField(max_length=255, choices=STATUS_CHOICES)


class ItemEncomenda(models.Model):
    encomenda = models.ForeignKey(Encomenda, on_delete=models.CASCADE)
    sneaker = models.ForeignKey(Sneaker, on_delete=models.CASCADE)
    quantidade = models.IntegerField()


class Favoritos(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    sneaker = models.ManyToManyField(Sneaker)

SneakerStore/store/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count, Q, Sum, F
from django.db.models.functions import Cast
from django.db.models import CharField
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.decorators.csrf import csrf_protect

from datetime import timedelta
import os

from .models import (
    Sneaker, Carrinho, ItemCarrinho, ItemEncomenda,
    Encomenda, Marca, Cliente, Tamanho, Categoria,
    EmpregadoLoja, Favoritos
)


def check_empregado_loja(user):
    return EmpregadoLoja.objects.filter(user_id=user.id).exists()


def check_cliente(user):
    return Cliente.objects.filter(user_id=user.id).exists()


def index(request):
    popular_sneakers = (
        Sneaker.objects.annotate(num_sales=Count('itemencomenda'))
        .order_by('-num_sales')[:8]
    )

    more_sneakers = Sneaker.objects.exclude(id__in=[s.id for s in popular_sneakers])[:4]

    context = {
        'popular_sneakers': popular_sneakers,
        'more_sneakers': more_sneakers,
    }

    return render(request, 'store/index.html', context)


@csrf_protect
def registar(request):
    if request.method == 'POST':

        nome = request.POST['nome']
        email = request.POST['email']
        password = request.POST['password']
        morada = request.POST['morada']
        telemovel = request.POST['telemovel']
        nif = request.POST['nif']
        imagem = request.FILES['imagem'] if 'imagem' in request.FILES else None
        categoria_preferida = request.POST['categoria_preferida']
        tamanho_preferido = request.POST['tamanho_preferido']
        marca_preferida = request.POST['marca_preferida']

        if not all([nome, email, password, morada, telemovel, nif, categoria_preferida, tamanho_preferido,
                    marca_preferida]):
            messages.error(request, 'Por favor, preencha todos os campos obrigatórios.')
            return redirect('store:registar')

        if User.objects.filter(username=email).exists():
            messages.error(request, 'Este email já está em uso. Por favor, tente outro.')
            return redirect('store:registar')

        if Cliente.objects.filter(nif=nif).exists():
            messages.error(request, 'Este NIF já está em uso. Por favor, tente outro.')
            return redirect('store:registar')

        user = User.objects.create_user(username=email, email=email, password=password)
        user.first_name = nome
        user.save()

        Cliente.objects.create(user=user, morada=morada, telemovel=telemovel, nif=nif, imagem=imagem,
                               categoria_preferida_id=categoria_preferida,
                               tamanho_preferido_id=tamanho_preferido, marca_preferida_id=marca_preferida)

        user = authenticate(username=email, password=password)
        login(request, user)

        messages.success(request, 'Registo concluído com sucesso! Bem-vindo(a) à Sneaker Store.')
        return redirect('store:index')

    else:

        marcas = Marca.objects.all()

        tamanhos = Tamanho.objects.all()

        categorias = Categoria.objects.all()

        context = {
            'marcas': marcas,
            'tamanhos': tamanhos,
            'categorias': categorias,
        }

        return render(request, 'store/registo.html', context)


def login_view(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=email, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, 'Login efetuado com sucesso!')

            if check_empregado_loja(user):
                return redirect('store:catalogo')
            else:
                return redirect('store:index')
        else:
            messages.error(request, 'Email ou senha incorretos. Por favor, tente novamente.')
            return redirect('store:login_view')
    else:
        return render(request, 'store/login.html')


@login_required
def perfil(request):
    return render(request, 'store/perfil.html')


@user_passes_test(check_cliente, login_url=reverse_lazy('store:login_view'))
def carrinho(request):
    carrinho = Carrinho.objects.filter(cliente=request.user.cliente, ativo=True).first()
    if not carrinho:
        return render(request, 'store/carrinho.html', {'itens_carrinho': [], 'cart_total': 0})

    data_atual = timezone.now().date()
    if carrinho.data_inatividade < data_atual:
        carrinho.ativo = False
        carrinho.save()
        novo_carrinho = Carrinho.objects.create(cliente=request.user.cliente, ativo=True)
        carrinho = novo_carrinho

    itens_carrinho = carrinho.itemcarrinho_set.select_related('sneaker').all().prefetch_related('sneaker')

    total_carrinho = itens_carrinho.aggregate(total_carrinho=Sum(F('quantidade') * F('sneaker__preco')))[
                         'total_carrinho'] or 0

    itens_carrinho = itens_carrinho.annotate(total_item=F('quantidade') * F('sneaker__preco'))

    context = {
        'itens_carrinho': itens_carrinho,
        'total_carrinho': total_carrinho,
    }
    return render(request, 'store/carrinho.html', context)


@user_passes_test(check_cliente, login_url=reverse_lazy('store:login_view'))
def adicionar_carrinho(request, sneaker_id):
    if request.method == "POST":
        sneaker = get_object_or_404(Sneaker, pk=sneaker_id)
        cliente = request.user.cliente
        quantidade = int(request.POST.get(f"quantidade-{sneaker_id}", 1))

        # Verificar se o carrinho existe para o cliente logado
        try:
            carrinho = Carrinho.objects.get(cliente=cliente, ativo=True)
        except Carrinho.DoesNotExist:
            # Se o carrinho não existir, verificar se existe algum carrinho inativo
            try:
                carrinho = Carrinho.objects.get(cliente=cliente, ativo=False)
                carrinho.ativo = True
            except Carrinho.DoesNotExist:
                # Se não houver carrinho inativo, criar um novo carrinho
                carrinho = Carrinho(cliente=cliente, ativo=True)

        # Atualizar a data de inatividade do carrinho
        carrinho.data_inatividade = timezone.now() + timedelta(days=7)
        carrinho.save()

        # Verificar se o item já está no carrinho
        try:
            item = ItemCarrinho.objects.get(carrinho=carrinho, sneaker=sneaker)
            item.quantidade += quantidade
            item.save()
            messages.info(request, f'O Sneaker {sneaker.nome} já está no carrinho! Quantidade atualizada.')
        except ItemCarrinho.DoesNotExist:
            # Se o item não estiver no carrinho, criar um novo item com quantidade 1
            item = ItemCarrinho.objects.create(carrinho=carrinho, sneaker=sneaker, quantidade=quantidade)
            messages.success(request, f'O Sneaker {sneaker.nome} foi adicionado ao carrinho!')

        # Colocar o carrinho na sessão
        request.session['carrinho_id'] = carrinho.id

        # Redirecionar para a página de onde veio o request
        return redirect(request.META.get('HTTP_REFERER', 'store:index'))


@login_required(login_url='store:login_view')
def favoritos(request):
    try:

        favoritos = Favoritos.objects.get(cliente=request.user.cliente)
    except Favoritos.DoesNotExist:

        messages.error(request, 'Parece que ainda não adicionou nenhum sneaker aos favoritos...')
        return redirect('store:index')

    context = {'favoritos': favoritos}
    return render(request, 'store/favoritos.html', context)


@user_passes_test(check_cliente, login_url=reverse_lazy('store:login_view'))
def adicionar_favoritos(request, sneaker_id):
    if request.method == "POST":
        sneaker = get_object_or_404(Sneaker, pk=sneaker_id)
        cliente = request.user.cliente

        try:
            favoritos = Favoritos.objects.get(cliente=cliente)
        except Favoritos.DoesNotExist:

            favoritos = Favoritos.objects.create(cliente=cliente)

        if favoritos.sneaker.filter(id=sneaker.id).exists():
            messages.info(request, f'O Sneaker {sneaker.nome} já está na sua lista de favoritos!')
        else:
            favoritos.sneaker.add(sneaker)
            favoritos.save()
            messages.success(request, f'O Sneaker {sneaker.nome} foi adicionado aos seus favoritos!')

        return redirect(request.META.get('HTTP_REFERER', 'store:index'))


@user_passes_test(check_cliente, login_url='store:login_view')
def remover_favoritos(request, sneaker_id):
    if request.method == "POST":
        sneaker = get_object_or_404(Sneaker, pk=sneaker_id)
        cliente = request.user.cliente

        try:
            favoritos = Favoritos.objects.get(cliente=cliente)
        except Favoritos.DoesNotExist:
            messages.info(request, 'Não tem nenhum favorito para remover.')
            return redirect('store:favoritos')

        if favoritos.sneaker.filter(id=sneaker.id).exists():
            favoritos.sneaker.remove(sneaker)
            messages.success(request, f'O Sneaker {sneaker.nome} foi removido dos favoritos!')
        else:
            messages.info(request, f'O Sneaker {sneaker.nome} não está na sua lista de favoritos.')

        return redirect('store:favoritos')


@login_required
def logout_view(request):
    logout(request)
    messages.success(request, 'Logout efetuado com sucesso!')
    return redirect('store:index')


@user_passes_test(check_cliente, login_url=reverse_lazy('store:login_view'))

SneakerStore/store/templates/Store/catalogo.html
{% extends './index.html' %}
{% load static %}
{% block banner %}
{% endblock %}
{% block content %}
<div class="cont-filters">
    <div class="filters-catalogo">
        <form method="get" action="">
            <label for="brand">Marca:</label>
            <select name="brand" id="brand">
                <option value="">Selecione a marca</option>
                {% for brand in brands %}
                <option value="{{ brand.id }}" {% if brand.id == selected_brand %} selected {% endif %}>{{ brand.nome }}
                </option>
                {% endfor %}
            </select>
            <label for="category">Categoria:</label>
            <select name="category" id="category">
                <option value="">Selecione a categoria</option>
                {% for category in categories %}
                <option value="{{ category.id }}" {% if category == selected_category %} selected {% endif %}>{{ category.nome }} </option>
                {% endfor %}
            </select>

            <label for="size">Tamanho:</label>
            <select name="size" id="size">
                <option value="">Selecione o tamanho</option>
                {% for size in sizes %}
                <option value="{{ size.id }}" {% if size.id == selected_size %} selected {% endif %}>{{ size.tamanho }}
                </option>
                {% endfor %}
            </select>

            <label for="search">Pesquisar:</label>
            <input type="text" name="search" id="search" placeholder="Digite o nome do sneaker">

            <button type="submit">Filtrar</button>
        </form>
    </div>
</div>
{% if not request.user.empregadoloja %}
<h1>Catálogo</h1>
{% endif %}
{% if sneakers %}
<div class="sneakers-cont">
    {% for sneaker in sneakers %}
    <div class="sneaker-card">
        <a href="{% url 'store:detalhes' sneaker.id %}">
            <img src="{% static sneaker.imagem %}" alt="{{ sneaker.nome }}">
            <h2>{{ sneaker.nome }}</h2>
            <p>Marca: {{ sneaker.marca.nome }}</p>
            <p>Categoria: {{ sneaker.categoria.nome }}</p>
            <p>Tamanho: {{ sneaker.tamanho.tamanho }}</p>
            <p>Preço: {{ sneaker.preco }}€</p>
             {% if request.user.empregadoloja %}
            <p>Quantidade em Stock: {{ sneaker.quantidade_stock }}</p>
            {% endif %}
        </a>
        <div class="card-actions">
            {% if user.is_authenticated and request.user.empregadoloja %}
            <a href="{% url 'store:editar_sneaker' sneaker.id %}" class="btn-admin btn-edit">Editar</a>
            <a href="{% url 'store:remover_sneaker' sneaker.id %}" class="btn-admin btn-remove">Remover</a>
        </div>
        {% else %}
        <div class="quantity-container">
            <button class="quantity-button" type="button"
                    onclick="diminuirQuantidade(event, '{{ sneaker.id }}')">-
            </button>
            <span class="qnt-nbr" id="quantidade-{{ sneaker.id }}">1</span>
            <button class="quantity-button" type="button"
                    onclick="aumentarQuantidade(event, '{{ sneaker.id }}')">+
            </button>
        </div>
    </div>
    <div class="add-cart-container">
        <form id="add-favorite-form-{{ sneaker.id }}" method="post"
              action="{% url 'store:adicionar_favoritos' sneaker.id %}">
            {% csrf_token %}
            <a href="#" class="favorite" onclick="submitFavoriteForm('{{ sneaker.id }}');">
                <i class="far fa-heart"></i>
                <i class="fas fa-heart hover-icon"></i>
            </a>
        </form>
        <form method="post" action="{% url 'store:adicionar_carrinho' sneaker.id %}">
            {% csrf_token %}
            <input type="hidden" id="quantidade-input-{{ sneaker.id }}" name="quantidade-{{ sneaker.id }}"
                   value="1">
            <button class="add-cart" type="submit">Adicionar ao carrinho</button>
        </form>
    </div>
    {% endif %}
</div>
{% endfor %}
</div>
<div class="pagination">
    {% if sneakers.has_previous %}
        <a href="?page={{ sneakers.previous_page_number }}">Página Anterior</a>
    {% endif %}
    <span class="current">Página {{ sneakers.number }} de {{ sneakers.paginator.num_pages }}</span>
    {% if sneakers.has_next %}
        <a href="?page={{ sneakers.next_page_number }}">Próxima Página</a>
    {% endif %}
</div>
{% else %}
<p class="enc-encomenda-none">Nenhum sneaker encontrado.</p>
{% endif %}
{% endblock %}

SneakerStore/store/templates/Store/index.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'store/css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="icon" type="image/png" href="{% static 'store/images/favicon.png' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'store/js/popup-messages.js' %}"></script>
    <script src="{% static 'store/js/quantity.js' %}"></script>
    <script src="{% static 'store/js/favorite.js' %}"></script>
    <title>{% block title %}Sneaker Store{% endblock %}</title>
</head>
<body>
{% if messages %}
<div id="django-messages" style="display:none;">
    {% for message in messages %}
    <div data-content="{{ message }}" data-type="{{ message.tags }}"></div>
    {% endfor %}
</div>
{% endif %}
{% if request.user.empregadoloja %}
<header>
    <nav>
        <ul>
            <li><a href="{% url 'store:catalogo' %}">Início</a></li>
            <li><a href="{% url 'store:adicionar_sneaker' %}">Adicionar Sneaker</a></li>
            <li><a href="{% url 'store:encomendas' %}">Gerir encomendas</a></li>
            <div class="profile-container">
                <div class="welcome-text">
                    Bem-vindo,<br> {{ request.user.first_name.split.0 }}
                </div>
                {% if request.user.empregadoloja.imagem %}
                <img class="profile-picture" src="{% static request.user.empregadoloja.imagem %}"
                     alt="Foto de perfil de{{ request.user.first_name }}">
                {% else %}
                <img class="profile-picture" src="{% static 'store/images/default_profile_pic.png' %}"
                     alt="Foto de perfil de{{ request.user.first_name }}">
                {% endif %}
                <li><a href="{% url 'store:perfil' %}">Ver Perfil</a></li>
                <li class="logout-btn"><a href="{% url 'store:logout' %}">Logout</a></li>
            </div>
        </ul>
    </nav>
</header>
{% else %}
<header>
    <nav>
        <ul>
            <li><a href="{% url 'store:index' %}">Início</a></li>
            <li><a href="{% url 'store:catalogo' %}">Catálogo</a></li>
            <li><a href="{% url 'store:sobre_nos' %}">Sobre nós</a></li>
            {% if request.user.cliente %}
            <li><a href="{% url 'store:recomendados' %}">Recomendados Para Si</a></li>
            <div class="profile-container">
                <div class="welcome-text">
                    Bem-vindo,<br> {{ request.user.first_name.split.0 }}
                </div>
                {% if request.user.cliente.imagem %}
                <img class="profile-picture" src="{% static request.user.cliente.imagem %}"
                     alt="Foto de perfil de{{ request.user.first_name }}">
                {% else %}
                <img class="profile-picture" src="{% static 'store/images/default_profile_pic.png' %}"
                     alt="Foto de perfil de{{ request.user.first_name }}">
                {% endif %}
                <li><a href="{% url 'store:perfil' %}">Ver Perfil</a></li>
                <li><a href="{% url 'store:encomendas' %}">Encomendas</a></li>

                <li class="logout-btn"><a href="{% url 'store:logout' %}">Logout</a></li>
            </div>
            {% else %}
            <li class="login-btn"><a href="{% url 'store:login_view' %}">Login</a></li>
            <li class="register-btn"><a href="{% url 'store:registar' %}">Registar</a></li>
            {% endif %}
            <li><a href="{% url 'store:carrinho' %}"><i class="fas fa-shopping-cart"></i></a></li>
            <li><a href="{% url 'store:favoritos' %}"><i class="fa fa-heart"></i></a></li>
        </ul>
    </nav>
</header>
{% block banner %}
<div class="banner">
    <img src="{% static 'store/images/banner3.jpg' %}" alt="Banner da Sneaker Store">
    <h1>Sneaker Store</h1>
    {% block catalog_button %}
    <a href="{% url 'store:catalogo' %}" class="btn">Ver Catálogo</a>
    {% endblock %}
</div>
{% endblock %}
{% endif %}
<main>
    {% block content %}
    <h1>Destaques</h1>
    <div class="sneakers-cont">
        {% for sneaker in popular_sneakers %}
        <div class="sneaker-card">
            <a href="{% url 'store:detalhes' sneaker.id %}">
                <img src="{% static sneaker.imagem %}" alt="{{ sneaker.nome }}">
                <h2>{{ sneaker.nome }}</h2>
                <p>Marca: {{ sneaker.marca.nome }}</p>
                <p>Categoria: {{ sneaker.categoria.nome }}</p>
                <p>Tamanho: {{ sneaker.tamanho.tamanho }}</p>
                <p>Preço: {{ sneaker.preco }}€</p>
            </a>
            <div class="card-actions">
                <div class="quantity-container">
                    <button class="quantity-button" type="button"
                            onclick="diminuirQuantidade(event, '{{ sneaker.id }}')">-
                    </button>
                    <span class="qnt-nbr" id="quantidade-{{ sneaker.id }}">1</span>
                    <button class="quantity-button" type="button"
                            onclick="aumentarQuantidade(event, '{{ sneaker.id }}')">+
                    </button>
                </div>
            </div>
            <div class="add-cart-container">
                <form id="add-favorite-form-{{ sneaker.id }}" method="post"
                      action="{% url 'store:adicionar_favoritos' sneaker.id %}">
                    {% csrf_token %}
                    <a href="#" class="favorite" onclick="submitFavoriteForm('{{ sneaker.id }}');">
                        <i class="far fa-heart"></i>
                        <i class="fas fa-heart hover-icon"></i>
                    </a>
                </form>
                <form method="post" action="{% url 'store:adicionar_carrinho' sneaker.id %}">
                    {% csrf_token %}
                    <input type="hidden" id="quantidade-input-{{ sneaker.id }}" name="quantidade-{{ sneaker.id }}"
                           value="1">
                    <button class="add-cart" type="submit">Adicionar ao carrinho</button>
                </form>
            </div>
        </div>

        {% endfor %}
    </div>

    <h1>Mais produtos</h1>
    <div class="sneakers-cont">
        {% for sneaker in more_sneakers %}
        <div class="sneaker-card">
            <a href="{% url 'store:detalhes' sneaker.id %}">
                <img src="{% static sneaker.imagem %}" alt="{{ sneaker.nome }}">
                <h2>{{ sneaker.nome }}</h2>
                <p>Marca: {{ sneaker.marca.nome }}</p>
                <p>Categoria: {{ sneaker.categoria.nome }}</p>
                <p>Tamanho: {{ sneaker.tamanho.tamanho }}</p>
                <p>Preço: {{ sneaker.preco }}€</p>
            </a>
            <div class="card-actions">
                <div class="quantity-container">
                    <button class="quantity-button" type="button"
                            onclick="diminuirQuantidade(event, '{{ sneaker.id }}')">-
                    </button>
                    <span class="qnt-nbr" id="quantidade-{{ sneaker.id }}">1</span>
                    <button class="quantity-button" type="button"
                            onclick="aumentarQuantidade(event, '{{ sneaker.id }}')">+
                    </button>
                </div>
            </div>
            <div class="add-cart-container">
                <form id="add-favorite-form-{{ sneaker.id }}" method="post"
                      action="{% url 'store:adicionar_favoritos' sneaker.id %}">
                    {% csrf_token %}
                    <a href="#" class="favorite" onclick="submitFavoriteForm('{{ sneaker.id }}');">
                        <i class="far fa-heart"></i>
                        <i class="fas fa-heart hover-icon"></i>
                    </a>
                </form>
                <form method="post" action="{% url 'store:adicionar_carrinho' sneaker.id %}">
                    {% csrf_token %}
                    <input type="hidden" id="quantidade-input-{{ sneaker.id }}" name="quantidade-{{ sneaker.id }}"
                           value="1">
                    <button class="add-cart" type="submit">Adicionar ao carrinho</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>

    {% endblock %}
</main>

<footer>
    <p> LEI-PL-3 &copy; 2023 Sneaker Store</p>
</footer>
</body>
</html>

SneakerStore/store/templates/Store/login.html
{% extends './index.html' %}

    {% block banner %}{% endblock %}
{% block title %}Login{% endblock %}
{% block content %}
<div class="form-container">
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label class="form-label" for="email">Email:</label>
      <input class="form-input" type="email" name="email" id="email" required>
    </div>
    <div class="form-group">
      <label class="form-label" for="password">Password:</label>
      <input class="form-input" type="password" name="password" id="password" required>
    </div>
    <button class="form-input" type="submit">Login</button>
  </form>
  <br>
  <p>Ainda não tem conta? <a href="{% url 'store:registar' %}">Registe-se</a></p>
</div>
{% endblock %}